# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HAP.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tHAP.proto\x12\x03HAP\"%\n\x0fSearchImagePath\x12\x12\n\nimage_path\x18\x01 \x01(\t\"%\n\x0fUpdateImagePath\x12\x12\n\nimage_path\x18\x01 \x01(\t\"(\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\"\x1e\n\x0cUpdateStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32|\n\nHAPService\x12\x39\n\x06Search\x12\x14.HAP.SearchImagePath\x1a\x17.HAP.PredictionResponse\"\x00\x12\x33\n\x06Update\x12\x14.HAP.UpdateImagePath\x1a\x11.HAP.UpdateStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HAP_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHIMAGEPATH']._serialized_start=18
  _globals['_SEARCHIMAGEPATH']._serialized_end=55
  _globals['_UPDATEIMAGEPATH']._serialized_start=57
  _globals['_UPDATEIMAGEPATH']._serialized_end=94
  _globals['_PREDICTIONRESPONSE']._serialized_start=96
  _globals['_PREDICTIONRESPONSE']._serialized_end=136
  _globals['_UPDATESTATUS']._serialized_start=138
  _globals['_UPDATESTATUS']._serialized_end=168
  _globals['_HAPSERVICE']._serialized_start=170
  _globals['_HAPSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
